// file to start up express app

import mongoose from 'mongoose';

import { app } from './app';

const start = async () => {
  // check for environmental variable generated by k8s in auth-depl file
  if (!process.env.JWT_KEY) {
    throw new Error('JWT_KEY must be defined');
  }

  // try to connect to db
  try {
    await mongoose.connect('mongodb://auth-mongo-srv:27017/auth', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: true,
    });
    console.log('connected to MongoDB');

    // if connection to db fails, log error
  } catch (err) {
    console.error(err);
  }

  // once connected, listen for oncoming traffic
  app.listen(3000, () => {
    console.log('Listening on port 3000!!!!!!!!');
  });
};

// when application loads up, run start function
start();
